### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by hubecker** [formatBCE/Respeaker-XVF3800-ESPHome-integration#20]
I receive the  following compiling error trying to build the latest version. 
I cleaned the build files, but didnt work.

`
INFO ESPHome 2026.3.0-dev
INFO Reading configuration /config/esphome/respeaker.yaml...
INFO Updating https://github.com/formatBCE/esphome@respeaker_microphone
INFO Updating https://github.com/formatBCE/Respeaker-XVF3800-ESPHome-integration@main
INFO Updating https://github.com/esphome/esphome@32708a2ee74f5ea4107448f62755004ad3e879c5
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Applying high-performance lwip settings (PSRAM guaranteed): 512KB TCP windows, 512 mailbox sizes
INFO Applying high-performance WiFi settings (PSRAM guaranteed): 512 RX buffers, 32 TX buffers
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 13 (registered: api=4, http_request_media_source=2, mdns=2, ota=1, sendspin_websocket_client=1, sendspin_websocket_server=3)
INFO Compiling app... Build path: /data/build/respeaker-xvf3800-assistant
Processing respeaker-xvf3800-assistant (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.2 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Reading CMake configuration...
Dependency Graph
|-- ESPMicroSpeechFeatures @ 1.1.0
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_reader.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_transfer_buffer.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/binary_sensor/binary_sensor.cpp.o
In file included from src/esphome/components/audio/audio_reader.cpp:1:
src/esphome/components/audio/audio_reader.h:12:10: fatal error: esp_http_client.h: No such file or directory

*******************************************************************************
* Looking for esp_http_client.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_http_client.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKesp_http_client.h
*
*******************************************************************************

   12 | #include <esp_http_client.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_reader.cpp.o] Error 1
========================== [FAILED] Took 5.40 seconds ==========================
`

**Comment by GinAndBacon** [comment]
Same after uoaatto 2026.2.0

`INFO ESPHome 2026.2.0
INFO Reading configuration /config/esphome/respeaker-xvf3800-assistant.yaml...
INFO Updating https://github.com/formatBCE/esphome@respeaker_microphone
INFO Updating https://github.com/formatBCE/Respeaker-XVF3800-ESPHome-integration@main
INFO Updating https://github.com/esphome/esphome@32708a2ee74f5ea4107448f62755004ad3e879c5
INFO Detected timezone 'America/Chicago'
INFO Generating C++ source...
INFO Applying high-performance lwip settings (PSRAM guaranteed): 512KB TCP windows, 512 mailbox sizes
INFO Applying high-performance WiFi settings (PSRAM guaranteed): 512 RX buffers, 32 TX buffers
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 13 (registered: api=4, http_request_media_source=2, mdns=2, ota=1, sendspin_websocket_client=1, sendspin_websocket_server=3)
INFO Deleting /data/build/respeaker-xvf3800-assistant/.pioenvs/respeaker-xvf3800-assistant/CMakeCache.txt
INFO Compiling app... Build path: /data/build/respeaker-xvf3800-assistant
Processing respeaker-xvf3800-assistant (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip)
--------------------------------------------------------------------------------
Platform Manager: Installing https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
INFO Installing https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: espressif32@55.3.37 has been installed!
INFO espressif32@55.3.37 has been installed!
INFO Version mismatch for tool-esptoolpy: 5.1.0 != 5.1.2
INFO Reinstalling tool-esptoolpy due to version mismatch
Created pioarduino Python virtual environment using uv: /root/.platformio/penv
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.1.2.zip
INFO Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.1.2.zip
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-esptoolpy@5.1.2 has been installed!
INFO tool-esptoolpy@5.1.2 has been installed!
Removing unused dependencies...
Library Manager: Removing ArduinoJson @ 7.4.2
INFO Removing ArduinoJson @ 7.4.2
Library Manager: ArduinoJson@7.4.2 has been removed!
INFO ArduinoJson@7.4.2 has been removed!
INFO Installing tools via idf_tools.py (this may take several minutes)...
Tool Manager: Installing file:///root/.platformio/tools/tool-esptoolpy
INFO Installing file:///root/.platformio/tools/tool-esptoolpy
Tool Manager: tool-esptoolpy@5.1.2 has been installed!
INFO tool-esptoolpy@5.1.2 has been installed!
INFO Tool tool-esptoolpy successfully installed
Installed esptool from tl-install path: /data/cache/platformio/packages/tool-esptoolpy
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.2 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Creating a new virtual environment for IDF Python dependencies using uv
Using Python 3.12.10 environment at: /root/.platformio/penv/.espidf-5.5.2
Installing ESP-IDF's Python dependencies with uv
Using Python 3.12.10 environment at: /root/.platformio/penv/.espidf-5.5.2
Resolved 27 packages in 587ms
Downloading pydantic-core (2.0MiB)
Downloading cryptography (4.0MiB)
 Downloaded pydantic-core
 Downloaded cryptography
Prepared 27 packages in 360ms
Installed 27 packages in 12ms
 + annotated-types==0.7.0
 + certifi==2026.1.4
 + cffi==2.0.0
 + charset-normalizer==3.4.4
 + click==8.3.1
 + colorama==0.4.6
 + cryptography==44.0.3
 + esp-idf-kconfig==2.5.2
 + idf-component-manager==2.4.6
 + idna==3.11
 + jsonref==1.1.0
 + psutil==7.2.2
 + pycparser==3.0
 + pydantic==2.12.5
 + pydantic-core==2.41.5
 + pydantic-settings==2.13.0
 + pyparsing==3.3.2
 + python-dotenv==1.2.1
 + requests==2.32.5
 + requests-file==3.0.1
 + requests-toolbelt==1.0.0
 + ruamel-yaml==0.19.1
 + tqdm==4.67.3
 + truststore==0.10.4
 + typing-extensions==4.15.0
 + typing-inspection==0.4.2
 + urllib3==1.26.20
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- ESPMicroSpeechFeatures @ 1.1.0
|-- noise-c @ 0.1.10
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/aic3104/aic3104.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_frame_helper_noise.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_chunk.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_chunk_queue.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_decoder.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_reader.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_resampler.cpp.o
In file included from src/esphome/components/audio/audio_reader.cpp:1:
src/esphome/components/audio/audio_reader.h:12:10: fatal error: esp_http_client.h: No such file or directory

*******************************************************************************
* Looking for esp_http_client.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_http_client.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKesp_http_client.h
*
*******************************************************************************

   12 | #include <esp_http_client.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_reader.cpp.o] Error 1
========================= [FAILED] Took 30.73 seconds =========================`

**Comment by GinAndBacon** [comment]
I had this happen yesterday but could not remember the exact error. i did a restore from backup  of just the eaphome device builder and did not make the changes (I was messing with wake word probability numbers) and it built fineAfter updating to 2026.2.0, which does a complete rebuild and ran into this. No YAML changes. Its almost as doing a complete rebuild wipes something out in the build directory which is why a restore worked. this is obviously speculation on my part as I tried to implement the new tier changes per the release notesdid a restore to 2026.1.5 and was able to build. after updating to 2026.2.0 I received this with no yaml changes made

`INFO ESPHome 2026.2.0
INFO Reading configuration /config/esphome/respeaker-xvf3800-assistant.yaml...
INFO Updating https://github.com/formatBCE/esphome@respeaker_microphone
INFO Updating https://github.com/formatBCE/Respeaker-XVF3800-ESPHome-integration@main
INFO Updating https://github.com/esphome/esphome@32708a2ee74f5ea4107448f62755004ad3e879c5
INFO Detected timezone 'America/Chicago'
INFO Generating C++ source...
INFO Applying high-performance lwip settings (PSRAM guaranteed): 512KB TCP windows, 512 mailbox sizes
INFO Applying high-performance WiFi settings (PSRAM guaranteed): 512 RX buffers, 32 TX buffers
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 13 (registered: api=4, http_request_media_source=2, mdns=2, ota=1, sendspin_websocket_client=1, sendspin_websocket_server=3)
INFO Deleting /data/build/respeaker-xvf3800-assistant/.pioenvs/respeaker-xvf3800-assistant/CMakeCache.txt
INFO Compiling app... Build path: /data/build/respeaker-xvf3800-assistant
Processing respeaker-xvf3800-assistant (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip)
--------------------------------------------------------------------------------
Platform Manager: Installing https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
INFO Installing https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: espressif32@55.3.37 has been installed!
INFO espressif32@55.3.37 has been installed!
INFO Version mismatch for tool-esptoolpy: 5.1.0 != 5.1.2
INFO Reinstalling tool-esptoolpy due to version mismatch
Created pioarduino Python virtual environment using uv: /root/.platformio/penv
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.1.2.zip
INFO Installing https://github.com/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.1.2.zip
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-esptoolpy@5.1.2 has been installed!
INFO tool-esptoolpy@5.1.2 has been installed!
Removing unused dependencies...
Library Manager: Removing ArduinoJson @ 7.4.2
INFO Removing ArduinoJson @ 7.4.2
Library Manager: ArduinoJson@7.4.2 has been removed!
INFO ArduinoJson@7.4.2 has been removed!
INFO Installing tools via idf_tools.py (this may take several minutes)...
Tool Manager: Installing file:///root/.platformio/tools/tool-esptoolpy
INFO Installing file:///root/.platformio/tools/tool-esptoolpy
Tool Manager: tool-esptoolpy@5.1.2 has been installed!
INFO tool-esptoolpy@5.1.2 has been installed!
INFO Tool tool-esptoolpy successfully installed
Installed esptool from tl-install path: /data/cache/platformio/packages/tool-esptoolpy
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.2 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Creating a new virtual environment for IDF Python dependencies using uv
Using Python 3.12.10 environment at: /root/.platformio/penv/.espidf-5.5.2
Installing ESP-IDF's Python dependencies with uv
Using Python 3.12.10 environment at: /root/.platformio/penv/.espidf-5.5.2
Resolved 27 packages in 587ms
Downloading pydantic-core (2.0MiB)
Downloading cryptography (4.0MiB)
 Downloaded pydantic-core
 Downloaded cryptography
Prepared 27 packages in 360ms
Installed 27 packages in 12ms
 + annotated-types==0.7.0
 + certifi==2026.1.4
 + cffi==2.0.0
 + charset-normalizer==3.4.4
 + click==8.3.1
 + colorama==0.4.6
 + cryptography==44.0.3
 + esp-idf-kconfig==2.5.2
 + idf-component-manager==2.4.6
 + idna==3.11
 + jsonref==1.1.0
 + psutil==7.2.2
 + pycparser==3.0
 + pydantic==2.12.5
 + pydantic-core==2.41.5
 + pydantic-settings==2.13.0
 + pyparsing==3.3.2
 + python-dotenv==1.2.1
 + requests==2.32.5
 + requests-file==3.0.1
 + requests-toolbelt==1.0.0
 + ruamel-yaml==0.19.1
 + tqdm==4.67.3
 + truststore==0.10.4
 + typing-extensions==4.15.0
 + typing-inspection==0.4.2
 + urllib3==1.26.20
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- ESPMicroSpeechFeatures @ 1.1.0
|-- noise-c @ 0.1.10
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/aic3104/aic3104.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_frame_helper_noise.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_chunk.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_chunk_queue.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_decoder.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_reader.cpp.o
Compiling .pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_resampler.cpp.o
In file included from src/esphome/components/audio/audio_reader.cpp:1:
src/esphome/components/audio/audio_reader.h:12:10: fatal error: esp_http_client.h: No such file or directory

*******************************************************************************
* Looking for esp_http_client.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_http_client.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKesp_http_client.h
*
*******************************************************************************

   12 | #include <esp_http_client.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/respeaker-xvf3800-assistant/src/esphome/components/audio/audio_reader.cpp.o] Error 1
========================= [FAILED] Took 30.73 seconds =========================`

**Comment by GinAndBacon** [comment]
Confirmed working on 2026.2.1 after updating the yaml to the [latest version](https://github.com/formatBCE/Respeaker-XVF3800-ESPHome-integration/blob/main/config/respeaker-xvf-satellite-example.yaml) updated yesterday. 

<img width="286" height="134" alt="Image" src="https://github.com/user-attachments/assets/53642bae-9151-4347-b137-9954943da1ef" />
